modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
  issueTrackerURL="https://github.com/BlakeBr0/MysticalAgradditions/issues"
  modId="mysticalagradditions"
  version="${file.jarVersion}"
  displayName="Mystical Agradditions"
  # updateJSONURL="http://myurl.me/"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions"
  # logoFile="examplemod.png"
  authors="BlakeBr0"
  credits="Mark719, xun468"
  description='''
  Grow all your resources!
  '''

  [[dependencies.mysticalagradditions]]
      modId="forge"
      mandatory=true
      versionRange="[38.0,)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.mysticalagradditions]]
      modId="minecraft"
      mandatory=true
      versionRange="[1.18,1.19)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.mysticalagradditions]]
      modId="cucumber"
      mandatory=true
      versionRange="[4.1.10,)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.mysticalagradditions]]
      modId="mysticalagriculture"
      mandatory=true
      versionRange="[4.2.1,)"
      ordering="AFTER"
      side="BOTH"